apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: gmajbdt7f-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-dotnet-basic:2993d9e6f2f4d42db96e5bcca6d6d4adc6a5f4f1@sha256:ca37a7f743423a92b81e22aef9cb8bf539a267f39e0f4b23ce31951504f76853
          name: container-image
